variable env {}
variable resource_group_name {}
variable location {}
variable subnet_id {}
variable private_ip_address {}
variable profile {}
variable backend_http_port {}
variable probe_host {}
variable probe_path {}
variable probe_host_backend {}
variable backend_http_probe_name {}
variable policy_name {}
variable region {}
variable "ip_address_list" {}
